Given an m$×$n matrix A and and 1$×$n vector v, subtract v from every row of A.

---



In [2]:
import numpy as np
import numpy.matlib

A = np.ones((5,5))
B = np.zeros((5,5))
C = np.zeros((5,5))
D = np.zeros((5,5))
v = np.arange(5)
(m, n) = A.shape

for i in range(m):
  B[i,:] = A[i,:] - v

C = A - np.matlib.repmat(v,5,1)

D = A - v

print(A)
print(v)
print(D)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4]
[[ 1.  0. -1. -2. -3.]
 [ 1.  0. -1. -2. -3.]
 [ 1.  0. -1. -2. -3.]
 [ 1.  0. -1. -2. -3.]
 [ 1.  0. -1. -2. -3.]]


Given an m × n matrix A, create a matrix B of the same size containing all zeros, and then copy into B the elements of A that are greater than zero

In [3]:
A = np.array([[-1, 5, 4], [-4, 6, -9], [0, 2, -4]])
(m, n) = A.shape
B = np.zeros_like(A)
C = np.zeros_like(A)

for i in range(m):
  for j in range(n):
    if A[i, j] > 0:
      B[i, j] = A[i, j]

C[A>0] = A[A>0]

print(A)
print(C)

[[-1  5  4]
 [-4  6 -9]
 [ 0  2 -4]]
[[0 5 4]
 [0 6 0]
 [0 2 0]]


Given a 1$\times$n vector v, create a vector w of the same size containing all zeros, sum up every two consecutive terms of v and then write into w

In [4]:
v = np.array([10, 30, 50, 40, 20])
#             -   10  30  50  40
w = np.zeros_like(v)
u = np.zeros_like(v)
n = v.size
print(n)
#        w = [40 80 90 60 0]
for i in range(n-1):
  w[i] = v[i] + v[i+1]
print(w)

u[:-1] = v[1:] + v[:-1]
print(u)


5
[40 80 90 60  0]
[40 80 90 60  0]
